services:
  db:
    image: postgres:16
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/booking
      PORT: 7642
    ports:
      - "7642:7642"
    command: >
      sh -c "yarn prisma migrate deploy && node dist/main.js"

    volumes:
      - .:/app
volumes:
  postgres_data:
